=head1 NAME

Config::Model::models::Debian::Dpkg::Control - Configuration class Debian::Dpkg::Control

=head1 VERSION

version 2.023

=head1 DESCRIPTION

Configuration classes used by L<Config::Model>

=head1 Elements

=head2 source - package source description

I<< Optional. Type node.  >>

=head2 binary - package binary description

I<< Optional. Type hash of node.  >>

=head1 SEE ALSO

=over

=item *

L<cme>

=item *

L<Config::Model::models::Debian::Dpkg::Control::Binary>

=item *

L<Config::Model::models::Debian::Dpkg::Control::Source>

=back

=head1 AUTHOR

=over

=item Dominique Dumont


=back

=head1 COPYRIGHT

=over

=item 2010,2011 Dominique Dumont


=back

=head1 LICENSE

=over

=item LGPL2


=back

=cut
