language: perl
perl:
  - "5.24"
  - "5.22"
  - "5.20"
  - "5.18"
  - "5.16"
  - "5.14"
#  - "5.12"
#  - "5.10"
 
install:
   - cpanm --quiet --notest Dist::Zilla 
   - cpanm --quiet --notest Config::Model::Tester 
   - cpanm --quiet --notest MouseX::NativeTraits 
   - cpanm --quiet --notest MouseX::StrictConstructor
   - cpanm --quiet --notest Carp::Assert::More
   - cpanm --quiet --notest Pod::POM
   - cpanm --quiet --notest Pod::Elemental::Transformer::List
   - cpanm --quiet --notest Dist::Zilla::Plugin::Run::BeforeBuild
   - "dzil authordeps | cpanm --verbose --notest"
   - "dzil listdeps   | cpanm --verbose"

script:
  - dzil smoke --release --author

notifications:
  email:
    recipients:
      - jluis@cpan.org
    on_success: change
    on_failure: always
