language: perl
perl:
#  - "5.24"
#  - "5.22"
#  - "5.20"
#  - "5.18"
#  - "5.16"
  - "5.14"
#  - "5.12"
#  - "5.10"

sudo: required

install:
   - cpanm --quiet --notest --skip-satisfied Dist::Zilla 
   - cpanm --quiet --notest --skip-satisfied Config::Model::Tester 
   - cpanm --quiet --notest --skip-satisfied Mouse
   - cpanm --quiet --notest --skip-satisfied MouseX::NativeTraits 
   - cpanm --quiet --notest --skip-satisfied MouseX::StrictConstructor
   - cpanm --quiet --notest --skip-satisfied Carp::Assert
   - cpanm --quiet --notest --skip-satisfied Carp::Assert::More
   - cpanm --quiet --notest --skip-satisfied Pod::POM
   - cpanm --quiet --notest --skip-satisfied Pod::Elemental::Transformer::List
   - cpanm --quiet --notest --skip-satisfied Log::Log4perl
   - cpanm --quiet --notest --skip-satisfied Dist::Zilla::Plugin::Run::BeforeBuild
   - sudo apt install -y libfuse-dev
   - cpanm --quiet --notest --skip-satisfied Fuse
   - "dzil authordeps --missing | cpanm --notest "
   - "dzil listdeps   --missing | cpanm --notest "

script:
  - dzil smoke --release --author

notifications:
  email:
    recipients:
      - jluis@cpan.org
    on_success: change
    on_failure: always
