language: perl
perl:
  - "5.24"
  - "5.22"
  - "5.20"
  - "5.18"
  - "5.16"
  - "5.14"
  - "5.12"
  - "5.10"
 
install:
   - cpanm --quiet --notest --skip-satisfied Dist::Zilla 
   - cpanm --notest --skip-satisfied Config::Model::Tester 
   - cpanm --notest --skip-satisfied MouseX::NativeTraits MouseX::StrictConstructor
   - cpanm --notest --skip-satisfied Carp::Assert::More
   - cpanm --notest --skip-satisfied Pod::POM Pod::Elemental::Transformer::List
   - "dzil authordeps | cpanm --verbose --notest --skip-satisfied"
   - "dzil listdeps   | cpanm --verbose"

script:
  - dzil smoke --release --author

notifications:
  email:
    recipients:
      - jluis@cpan.org
    on_success: change
    on_failure: always
