language: perl
perl:
  - "5.24"
  - "5.22"
  - "5.20"
  - "5.18"
  - "5.16"
  - "5.14"


install:
   - cpanm --quiet --notest Dist::Zilla 
   - "dzil authordeps --missing | cpanm --notest "
   - "dzil listdeps --missing | cpanm --notest "
   - cpanm --quiet --notest --skip-satisfied MouseX::NativeTraits

script:
  - dzil smoke --release --author
