=head1 Installation

=head2 Debian or Ubuntu

L<cme> and most L<Config::Model> modules are provided as Debian package. The following
command will install the framework and all available models and UIs:

  sudo apt install --install-recommends --install-suggests cme

=head2 Other systems

For other systems, you should install L<Config::Model> from CPAN:

  cpanp install App::Cme
  cpanp install Config::Model
