=head1 NAME

Config::Model::models::Multistrap::Section - Configuration class Multistrap::Section

=head1 VERSION

version 2.023

=head1 DESCRIPTION

Configuration classes used by L<Config::Model>

=head1 Elements

=head2 packages

I<< Optional. Type list of uniline.  >>

=head2 components

I<< Optional. Type list of uniline.  >>

=head2 source

I<< Optional. Type uniline.  >>

=head2 keyring

I<< Optional. Type uniline.  >>

=head2 suite

I<< Optional. Type uniline.  >>

=head2 omitdebsrc

I<< Optional. Type boolean.  >>

=head1 SEE ALSO

=over

=item *

L<cme>

=back

=cut
