=head1 NAME

Config::Model::models::Fstab - Configuration class Fstab

=head1 VERSION

version 2.023

=head1 DESCRIPTION

Configuration classes used by L<Config::Model>

static information about the filesystems. fstab contains descriptive information about the various file systems. 


=head1 Elements

=head2 fs - specification of one file system

Each "fs" element contain the information about one filesystem. Each filesystem is referred in this model by a label constructed by the fstab parser. This label cannot be stored in the fstab file, so if you create a new file system, the label you will choose may not be stored and will be re-created by the fstab parser. I<< Optional. Type hash of node.  >>

=head1 SEE ALSO

=over

=item *

L<cme>

=item *

L<Config::Model::models::Fstab::FsLine>

=back

=head1 AUTHOR

=over

=item Dominique Dumont


=back

=head1 COPYRIGHT

=over

=item 2010,2011 Dominique Dumont


=back

=head1 LICENSE

=over

=item LGPL2


=back

=cut
